In [67]:
!conda install pytorch cpuonly -c pytorch

^C


In [59]:
!conda install numpy

Channels:
 - defaults
Platform: win-64
Solving environment: ...working... done

# All requested packages already installed.



In [70]:
from transformers import GPT4Tokenizer

ImportError: cannot import name 'GPT4Tokenizer' from 'transformers' (C:\Users\RiccardelliScott\anaconda3\Lib\site-packages\transformers\__init__.py)

In [16]:
from transformers import AutoTokenizer, AutoModel
import torch
import torch.nn.functional as F

#Mean Pooling - Take attention mask into account for correct averaging
def mean_pooling(model_output, attention_mask):
    token_embeddings = model_output[0] #First element of model_output contains all token embeddings
    input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    return torch.sum(token_embeddings * input_mask_expanded, 1) / torch.clamp(input_mask_expanded.sum(1), min=1e-9)


# Sentences we want sentence embeddings for
# sentences = ['This is an example sentence', 'Each sentence is converted']
sentences = [
  "Beyond Mars (1 hr 15 min): Join space enthusiasts as they speculate about extraterrestrial life and the mysteries of distant planets.",
  "Jazz under stars (55 min): Experience a captivating night in New Orleans, where jazz melodies echo under the moonlit sky.",
  "Mysteries of the deep (1 hr 30 min): Dive with marine explorers into the uncharted caves of our oceans and uncover their hidden wonders.",
  "Rediscovering lost melodies (48 min): Journey through time to explore the resurgence of vinyl culture and its timeless appeal.",
  "Tales from the tech frontier (1 hr 5 min): Navigate the complex terrain of AI ethics, understanding its implications and challenges.",
  "The soundscape of silence (30 min): Traverse the globe with sonic explorers to find the world's most serene and silent spots.",
  "Decoding dreams (1 hr 22 min): Step into the realm of the subconscious, deciphering the intricate narratives woven by our dreams.",
  "Time capsules (50 min): Revel in the bizarre, endearing, and profound discoveries that unveil the quirks of a century past.",
  "Frozen in time (1 hr 40 min): Embark on an icy expedition, unearthing secrets hidden within the majestic ancient glaciers.",
  "Songs of the Sea (1 hr): Dive deep with marine biologists to understand the intricate whale songs echoing in our vast oceans."
]

# Load model from HuggingFace Hub
tokenizer = AutoTokenizer.from_pretrained('sentence-transformers/all-mpnet-base-v2')
model = AutoModel.from_pretrained('sentence-transformers/all-mpnet-base-v2')

# Tokenize sentences
encoded_input = tokenizer(sentences, padding=True, truncation=True, return_tensors='pt')

# Compute token embeddings
with torch.no_grad():
    model_output = model(**encoded_input)

# Perform pooling
sentence_embeddings = mean_pooling(model_output, encoded_input['attention_mask'])

# Normalize embeddings
sentence_embeddings = F.normalize(sentence_embeddings, p=2, dim=1)

print("Sentence embeddings:")
print(sentence_embeddings)
print(sentence_embeddings.shape)


Sentence embeddings:
tensor([[ 0.0136, -0.0204,  0.0139,  ...,  0.0396, -0.0144, -0.0282],
        [-0.0172, -0.0105, -0.0037,  ..., -0.0055,  0.0184, -0.0445],
        [ 0.0071,  0.0127, -0.0220,  ...,  0.0230, -0.0150,  0.0017],
        ...,
        [ 0.0074,  0.0544, -0.0129,  ...,  0.0328, -0.0091, -0.0135],
        [-0.0039,  0.0338,  0.0003,  ...,  0.0374, -0.0225,  0.0062],
        [ 0.0340,  0.0738, -0.0202,  ...,  0.0273,  0.0099, -0.0370]])
torch.Size([10, 768])


In [69]:
sentence_test = ["saxophone nightclub"]
tokenizer = AutoTokenizer.from_pretrained('sentence-transformers/all-mpnet-base-v2')
model = AutoModel.from_pretrained('sentence-transformers/all-mpnet-base-v2')
# tokenizer = GPT4Tokenizer.from_pretrained('Xenova/text-embedding-ada-002')
# model = AutoModel.from_pretrained('Xenova/text-embedding-ada-002')

# Tokenize sentences
encoded_input = tokenizer(sentence_test, padding=True, truncation=True, return_tensors='pt')

# Compute token embeddings
with torch.no_grad():
    model_output = model(**encoded_input)

# Perform pooling
query_embeddings = mean_pooling(model_output, encoded_input['attention_mask'])

# Normalize embeddings
query_embeddings = F.normalize(query_embeddings, p=1, dim=1)

print("query embeddings:")
# print(sentence_test_embeddings)
print(query_embeddings.shape)

NameError: name 'GPT4Tokenizer' is not defined

In [32]:
input1 = torch.randn(100, 128)
input2 = torch.randn(100, 128)
print(input1.shape)
cos = nn.CosineSimilarity(dim=1, eps=1e-6)
output = cos(input1, input2)
print(output)

torch.Size([100, 128])
tensor([-0.0453,  0.1228,  0.0009,  0.0729, -0.0021, -0.0017, -0.1844, -0.1232,
        -0.0430,  0.0496, -0.1468, -0.1631, -0.1360, -0.0114,  0.0740,  0.1488,
         0.1291, -0.0026, -0.0227, -0.0555,  0.1586,  0.1117, -0.0732, -0.0257,
        -0.0055,  0.0949, -0.1227,  0.0037,  0.0337, -0.0376,  0.0134, -0.0530,
        -0.0272, -0.0910, -0.1145,  0.0276, -0.0508,  0.0386,  0.0323, -0.1203,
         0.0397,  0.0400,  0.0333,  0.0293,  0.0678,  0.1561, -0.0478,  0.0617,
         0.0923,  0.2419, -0.0097,  0.1034,  0.1016,  0.0121, -0.0575, -0.0545,
         0.0419,  0.0501,  0.0737, -0.1744,  0.1137, -0.0907,  0.0493, -0.1207,
         0.0783,  0.0104,  0.0577, -0.0845, -0.1083, -0.0455, -0.0288, -0.0405,
         0.1506, -0.0573,  0.0980,  0.1049, -0.1113, -0.0095,  0.0667,  0.0445,
         0.0080,  0.1370, -0.0025, -0.0019,  0.0292, -0.0431,  0.0181,  0.0515,
        -0.0459, -0.1767,  0.0152, -0.0077,  0.1535,  0.0208,  0.1274, -0.0894,
        -0.0616, 

In [60]:
best_i, best_score = 0, 0
for i, sentence_embedding in enumerate(sentence_embeddings):
    # print(sentence_embedding.shape)
    # print(sentence_test_embeddings[0].shape)
    cos = nn.CosineSimilarity(dim=0, eps=1e-6)
    score = cos(sentence_embedding, query_embeddings[0])
    if score > best_score:
        best_score = score
        best_i = i
    print(score)
print(best_i, best_score)
print(sentences[best_i])

tensor(0.1847)
tensor(0.4688)
tensor(0.1160)
tensor(0.3309)
tensor(0.0200)
tensor(0.2734)
tensor(0.0690)
tensor(0.1463)
tensor(0.0623)
tensor(0.2213)
1 tensor(0.4688)
Jazz under stars (55 min): Experience a captivating night in New Orleans, where jazz melodies echo under the moonlit sky.


In [66]:
cos = nn.CosineSimilarity(dim=1, eps=1e-6)
scores = cos(sentence_embeddings, query_embeddings[0])
print(scores)
best_i = torch.argmax(scores)
print(best_i)
print(sentences[best_i])

tensor([0.1847, 0.4688, 0.1160, 0.3309, 0.0200, 0.2734, 0.0690, 0.1463, 0.0623,
        0.2213])
tensor(1)
Jazz under stars (55 min): Experience a captivating night in New Orleans, where jazz melodies echo under the moonlit sky.


## Next Steps

Use a vector database

or use a nearest neighbors algorithm